"""Post triage summaries to Slack using Block Kit."""

from __future__ import annotations

import logging
from typing import Any

import httpx

from kairos_agent.config import SlackConfig

logger = logging.getLogger("kairos_agent")


def _truncate(text: str, max_len: int = 2900) -> str:
    """Truncate text to fit Slack block limits (3000 chars per section)."""
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def build_slack_blocks(alert_info: dict, summary: str) -> list[dict[str, Any]]:
    """Build Slack Block Kit blocks for the triage summary."""
    title = alert_info.get("title", "Incident Alert")
    service = alert_info.get("service_name", "unknown")
    urgency = alert_info.get("urgency", "high")
    triggered_at = alert_info.get("triggered_at", "N/A")
    pd_url = alert_info.get("html_url", "")

    urgency_emoji = ":red_circle:" if urgency == "high" else ":large_yellow_circle:"

    blocks: list[dict[str, Any]] = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"Incident: {title[:148]}",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Service:*\n{service}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Urgency:*\n{urgency_emoji} {urgency}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Triggered:*\n{triggered_at}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Incident:*\n<{pd_url}|View in PagerDuty>" if pd_url else "*Incident:*\nN/A",
                },
            ],
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Triage Summary*\n{_truncate(summary)}",
            },
        },
        {"type": "divider"},
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "Generated by *kairos-agent* v0.1.0 | AI-powered incident triage",
                }
            ],
        },
    ]

    return blocks


async def notify_slack(
    alert_info: dict,
    summary: str,
    slack_config: SlackConfig,
) -> None:
    """Post triage summary to Slack via incoming webhook."""
    blocks = build_slack_blocks(alert_info, summary)
    title = alert_info.get("title", "Incident Alert")

    payload = {
        "text": f"Incident triage: {title}",  # Fallback for notifications
        "blocks": blocks,
    }

    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.post(slack_config.webhook_url, json=payload)

    if resp.status_code != 200:
        logger.error(
            "Slack webhook returned %d: %s", resp.status_code, resp.text
        )
        raise RuntimeError(f"Slack notification failed: {resp.status_code}")

    logger.info("Triage summary posted to Slack for: %s", title)
